#! /bin/bash

# Startup Script to run the game
if [ ! -d "./node_modules" ];then
    npm i
fi

# Clean-up before build if required
build_folders=$(find . -maxdepth 1 -type d -regex "./build.*")

echo "$build_folders" | while IFS= read -r folder; do
    echo "Removing Old Build Directory $folder"
    rm -rf "$folder"
done

# Build the front-end react setup to generate static files
npm run build
mkdir build_folder
cp -r build/. build_folder

# Start the server
nodemon server/server.js